# Lable Encoding involves converting each value of a categorical column into a unique integer. For example, if a column has three categories: "red", "blue", and "green", label encoding would convert these to 0, 1, and 2 respectively.

In [23]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 


In [24]:
df=pd.DataFrame({
    "color":["red","blue","green","green","red","blue","green","red"]
})


In [25]:
encoder=LabelEncoder()

In [26]:
label_Encoder=encoder.fit_transform(df[["color"]])
label_Encoder

/opt/anaconda3/envs/ai-venv/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0, 1, 2])

In [22]:
label_Encoder.transform([["red"]])


AttributeError: 'numpy.ndarray' object has no attribute 'transform'

# ORDINAL ENCODING 

# The Problem with the Lablel Encoding is that it can mislead machine learning algorithms into interpreting the encoded values as having a mathematical relationship, which may not be accurate for categorical data. For instance, in the previous example, the algorithm might assume that "blue" (1) is somehow "greater than" "red" (0) and "green" (2) is "greater than" both, which is not the case for nominal categories. This can lead to incorrect model assumptions and potentially poor performance.
# Ordinal Encoding is a technique used to convert categorical variables into numerical format, where the categories have a meaningful order or ranking. In ordinal encoding, each category is assigned a unique integer value based on its order or rank. For example, if a column has three categories: "low", "medium", and "high", ordinal encoding would convert these to 0, 1, and 2 respectively, reflecting their inherent order.

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
df=pd.DataFrame({
    "size":["small","medium","large","medium","small","large","large","small"]
})

ordinal_Encoder=OrdinalEncoder(categories=[["small","medium","large"]])
ordinal_Encoder.fit_transform(df[["size"]])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.]])

In [31]:
ordinal_Encoder.transform([["medium"]])

/opt/anaconda3/envs/ai-venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1.]])